function quick_adcp_vel(adcpfile, bottomfile, tlim, tbin, theta)

% usage ex:
% quick_adcp_vel('adcp_20120808.mat', '../ECHO-SOUNDER/bottom.mat', [datenum(2012, 08, 08, 10, 15, 0) datenum(2012, 08, 08, 22, 45, 0)], 600, 33.5)
%   
% bottom.mat is generated by bottomDetection.m
% tbin in seconds
  
MH = datenum(2012, 08, 08, 11, 04, 00);
MB = datenum(2012, 08, 08, 17, 03, 00);

    
tbin = tbin/86400; % tbin in days    
load(adcpfile)    
load(bottomfile)

U = ADCP.east_vel;
V = ADCP.north_vel;
mtime = ADCP.mtime;
z = ADCP.config.ranges;

if bottomTime(1)>tlim(1) | mtime(1)>tlim(1)
    tlim(1) = max([bottomTime(1), mtime(1)]);
end
if bottomTime(end)<tlim(2) | mtime(end)<tlim(2)
    tlim(2) = min([bottomTime(end), mtime(end)]);
end
    
timeVec = tlim(1):tbin:tlim(2);


% correct for boat drift
[ucor, vcor] = adcp_velcor(U, V, mtime, '../GPS/20120808');

%I = find(mtime >= tlim(1) & mtime <= tlim(2));
[valong, vcross]=rotate_vecd(ucor, vcor, theta);

Ubin = nan(length(z), length(timeVec));
Vbin = nan(length(z), length(timeVec));


% Remove bottom
for i = 1:length(mtime)
    [Y, I] = min(abs(mtime(i)-bottomTime));
    bot(i) = bottom(I);
    I = find(z>=bot(i));
    valong(I,i) = NaN;
    vcross(I,i) = NaN;    
end

% compute for Z
for i = 1:length(timeVec)
    I = find(mtime>=timeVec(i)-tbin/2 & mtime<=timeVec(i)+tbin/2);
    Ubin(:,i) = nanmean(valong(:,I), 2);
    Vbin(:,i) = nanmean(vcross(:,I), 2);
end


% compute for HAB
hab = 0:z(2)-z(1):max(bot);
Uhab = nan(length(hab), length(timeVec));
Vhab = nan(length(hab), length(timeVec));
for i = 1:length(timeVec)
    I = find(~isnan(Ubin(:,i))==1);
    Uvec = flipud(Ubin(1:I(end), i));
    Vvec = flipud(Vbin(1:I(end), i));
    Uhab(1:length(I), i) = Uvec;
    Vhab(1:length(I), i) = Vvec;
end




figure(1)
clf
set(gcf,'PaperUnits','centimeters','PaperPosition',[10 10 30 15])
subplot(211)
imagesc(timeVec, z, Ubin*100)
caxis([-25 25])
set(gca, 'xticklabel', [])
c = colorbar;%('position', [.89 .15 .025 .2]);
ti = ylabel(c,'{U (cm s^{-1})}', 'FontSize', 10);
xlim([tlim])
ylabel('z(m)')

subplot(212)
imagesc(timeVec, z, Vbin*100)
caxis([-25 25])
datetick('x')
c = colorbar;%('position', [.89 .15 .025 .2]);
ti = ylabel(c,'{V (cm s^{-1})}', 'FontSize', 10);
xlim([tlim])
text(MH, 110, '*', 'color', [1 1 1])
text(MH, 105, 'HT', 'color', [1 1 1])
text(MB, 110, '*', 'color', [1 1 1])
text(MB, 105, 'LT', 'color', [1 1 1])
ylabel('z(m)')

print('-dpng', '-r300', 'onboardADCP_z.png');  
print('-depsc2', 'onboardADCP_z.eps');


figure(2)
clf
set(gcf,'PaperUnits','centimeters','PaperPosition',[10 10 30 15])
subplot(211)
imagesc(timeVec, hab, Uhab*100)
caxis([-25 25])
set(gca, 'xticklabel', [])
set(gca, 'ydir', 'normal')
c = colorbar;%('position', [.89 .15 .025 .2]);
ti = ylabel(c,'{U (cm s^{-1})}', 'FontSize', 10);
xlim([tlim])
ylim([0 80])
ylabel('hab(m)')

subplot(212)
imagesc(timeVec, hab, Vhab*100)
caxis([-25 25])
datetick('x')
c = colorbar;%('position', [.89 .15 .025 .2]);
ti = ylabel(c,'{V (cm s^{-1})}', 'FontSize', 10);
xlim([tlim])
ylim([0 60])
set(gca, 'ydir', 'normal')
text(MH, 0, '*', 'color', [0 0 0])
text(MH, -5, 'HT', 'color', [0 0 0])
text(MB, 0, '*', 'color', [0 0 0])
text(MB, -5, 'LT', 'color', [0 0 0])
ylabel('hab(m)')

print('-dpng', '-r300', 'onboardADCP_hab.png');  
print('-depsc2', 'onboardADCP_hab.eps');

keyboard